version: "3.0"
services:
  db:
    image: postgres:14
    restart: always
    container_name: "db"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: hackme
      POSTGRES_HOST: db
      POSTGRES_DB: pg
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
