"""Initial

Revision ID: c2feff80d4cd
Revises:
Create Date: 2021-12-07 14:29:15.336232

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c2feff80d4cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
                    sa.Column('chat_id', sa.String(), nullable=False),
                    sa.Column('chat_name', sa.String(length=255),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk__chats'))
                    )
    op.create_table('messages',
                    sa.Column('message_id', sa.String(), nullable=False),
                    sa.Column('user_from', sa.String(), nullable=False),
                    sa.Column('chat_from', sa.String(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.PrimaryKeyConstraint('message_id',
                                            name=op.f('pk__messages'))
                    )
    op.create_table('sessions',
                    sa.Column('rel_id', sa.BigInteger(), autoincrement=True,
                              nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('session_id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('rel_id',
                                            name=op.f('pk__sessions'))
                    )
    op.create_table('tasks',
                    sa.Column('task_id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('search_text', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('messages', sa.ARRAY(sa.String(), dimensions=1),
                              nullable=False),
                    sa.PrimaryKeyConstraint('task_id', name=op.f('pk__tasks'))
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('user_name', sa.String(length=255),
                              nullable=False),
                    sa.Column('password', sa.String(length=255),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__users')),
                    sa.UniqueConstraint('user_id',
                                        name=op.f('uq__users__user_id')),
                    sa.UniqueConstraint('user_name',
                                        name=op.f('uq__users__user_name'))
                    )
    op.create_table('users_chats_relations',
                    sa.Column('rel_id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('user_name', sa.String(length=255),
                              nullable=False),
                    sa.Column('chat_id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('rel_id', name=op.f(
                        'pk__users_chats_relations'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_chats_relations')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('sessions')
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
